server:
  host: "127.0.0.1"
  port: 8080

clients:
  waifu_im:
    enabled: true
    base_url: "https://api.waifu.im"
  waifu_pics:
    enabled: true
    base_url: "https://api.waifu.pics"
  nekos_moe:
    enabled: true
    base_url: "https://nekos.moe/api/v1"
  nekos_api:
    enabled: true
    base_url: "https://api.nekosapi.com/v4"
  pic_re:
    enabled: true
    base_url: "https://pic.re"
  purrbot_site:
    enabled: true
    base_url: "https://api.purrbot.site/v2"
