name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Build binaries
        run: |
          gox -osarch="linux/amd64 linux/arm64 windows/amd64 windows/arm64 darwin/amd64 darwin/arm64" -output="dist/booru-server-{{.OS}}-{{.Arch}}" ./cmd/server

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
